language: php

php:
  - "7.2.17"

services:
  - mysql

install:
  - wget https://get.symfony.com/cli/installer -O - | bash
  - export PATH="$HOME/.symfony/bin:$PATH"
  - composer install --no-interaction
  - echo "USE mysql;\nSET PASSWORD FOR 'root'@'localhost' = PASSWORD('${MYSQL_PASSWORD}');\nFLUSH PRIVILEGES;\n" | mysql -u root
  - echo "###> doctrine/doctrine-bundle ###" > .env.local_for_test
  - echo "DATABASE_URL=mysql://root:${MYSQL_PASSWORD}@127.0.0.1:3306/erp-asso-test" >> .env.local_for_test
  - echo "###< doctrine/doctrine-bundle ###" >> .env.local_for_test
  - echo "###> symfony/swiftmailer-bundle ###" >> .env.local_for_test
  - echo "MAILER_URL=null://localhost" >> .env.local_for_test
  - echo "###< symfony/swiftmailer-bundle ###" >> .env.local_for_test
  - ./server_start_aaasso.sh test&
  - ./bin/console doctrine:database:create --env=test
  - ./bin/console doctrine:migration:migrate --env=test --no-interaction

script:
  - ./vendor/bin/simple-phpunit
