language: php

php:
  - "7.2.17"

services:
  - mysql

install:
  - wget https://get.symfony.com/cli/installer -O - | bash
  - composer install --no-interaction
  - echo "USE mysql;\nSELECT host, user FROM mysql.user;\n" | mysql -u root
  - echo "USE mysql;\nSET PASSWORD FOR 'root'@'localhost' = PASSWORD('${MYSQL_PASSWORD}');\nFLUSH PRIVILEGES;\n" | mysql -u root
  - ./server_start_aaasso.sh travis
  - ./bin/console doctrine:database:create --env=travis
  - ./bin/console doctrine:migration:migrate --env=travis --no-interaction

script:
  - ./vendor/bin/simple-phpunit
