files:
  - source: /translations/messages.*.xlf
    translation: /translations/messages.%two_letters_code%.xlf
  - source: /translations/security.*.xlf
    translation: /translations/security.%two_letters_code%.xlf
  - source: /translations/validators.*.xlf
    translation: /translations/validators.%two_letters_code%.xlf
