imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

# Doctrine Configuration
doctrine:
    dbal:
        password: '%env(MYSQL_PASSWORD)%'

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
    firewalls:
        # replace 'main' by the name of your own firewall
        main:
            http_basic: ~
