# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # define the algorythm used to hash the password
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # define the class used to login
    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disable authentication for assets and the profiler
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            # activate the login page as page to authenticate
            form_login:
                login_path: /login
                check_path: /login
                success_handler: authentication_success_handler

            # activate the logout page as page to logout
            logout:
                path: /logout
                target: /
                success_handler: logout_success_handler

            # logout when the user changes
            logout_on_user_change: true

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/administration, roles: ROLE_ADMIN }